### ISSUE TITLE
gradle project sync failed

### ISSUE THREAD

**Issue by sgueniot** [paamand/GDAL#1]
Hello,
i'm trying to compile this project but I have an issue : 
```
CMake Error at CMakeLists.txt:10 (add_library): |  
-- | --
src/main/cpp/gdal_wrap.cpp |  
Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp |  
.hxx .in .txx |  
CMake Error: CMake can not determine linker language for target: gdalwrap
```
does anyone have an idea to fix this problem?

Thanks !

**Comment by sgueniot** [comment]
it's ok, i have to change path in CMakeLists.txt to link file in gdal module.
The path sould be add_library( gdalwrap SHARED ../submodules/gdal/gdal/swig/python/extensions/gdal_wrap.cpp )

**Comment by paamand** [comment]
Actually, the install.sh in submodules that will be called by building the installFromSources task should copy the relevant files to the main/cpp folder. E.g. your workaround should not be needed. I will look into why it is.

**Comment by sgueniot** [comment]
thanks :). And i failed to build the other libraries ,libosr.so and libogr.so . Do you know how i can compile this two libraries ? I tried to uncomment in cmakelist but  it's not working :(

**Comment by paamand** [comment]
Build the submodule libraries with the submodules/install.sh. This can be
done by `gradlew installFromSource`.

The script builds and packages the libraries and headers with wrapper code
into the main project that can then be build to link it together in an .aar
file ready to import.

//R

tor. 7. feb. 2019 08.49 skrev Sylvain Guéniot <notifications@github.com>:

**Comment by paamand** [comment]
The install.sh did not create the necessary main/cpp/include folder which is required for the binding cpp files. This is fixed now, and the project syncs.
Ubuntu 18.04
Android Studio 3.3

**Comment by sgueniot** [comment]
It's working (Archlinux, Android Studio 3.2.1)
however, I still can't get libosr and libogr.  in the jnilibs folder, I only have libgdal, libgalalljni, libproj. The aar also does not contain these libraries

**Comment by sgueniot** [comment]
These 2 libraries seem to be useless (included in libgdal ?). Anyway, it works in my test. Thank you. Next step, compile the 64-bit versions...
thanks you again.
